### ISSUE TITLE
Has this tool been abandoned by original author or has the website just been hacked?

### ISSUE THREAD

**Issue by IceKickr** [sarah-walker-pcem/pcem#31] opened 2021-06-14 00:27 UTC
Unable to access the web site and wiki site says "this has been discontinued as of 6/12"

**Comment by laetemn** [comment] 2021-06-14 00:49
ALL files...

http://pcem-emulator.co.uk/files/

**Comment by mirrornoir** [comment] 2021-06-14 04:30
I explained a bit more here: https://github.com/sarah-walker-pcem/pcem/issues/32#issuecomment-860332368

**Comment by pcem-maintainer** [comment] 2021-06-29 02:30
Duplicate of #32

**Closed by pcem-maintainer** 2021-06-29 02:30 UTC
