### ISSUE TITLE
Voodoo 3/Banshee: attempting to run Gex 3D: Enter the Gecko crashes PCem

### ISSUE THREAD

**Issue by unreal9010** [sarah-walker-pcem/pcem#21] opened 2021-06-03 20:58 UTC
**Describe the bug**
Using either Voodoo 3 or Voodoo Banshee crashes PCem as soon as Gex 3D: Enter the Gecko (either a demo or a full version) is about to be started. 
Happens with any version of Direct X or GPU drivers.
For comparison: the game works great with Voodoo 1 and Voodoo 2 on the same emulated machine.  
Same thing described above also happens with Starshot: Space Circus.

**To Reproduce**
1. Start PCem
2. Launch the emulated machine
3. Attempt to launch the game
4. PCem will crash

**Expected behavior**
Normal game launch

**Screenshots**

**Emulator configuration**
 - Machine:  GA-686BX
 - CPU: Pentium ll 233
 - Graphics/sound cards: Voodoo3, Voodoo Banshee, SB 128
 - Windows 95

**Host machine**
 - OS: Windows 10
 - PCem v17
 - i7 6700, GeForce GTX 1060 

**Additional context**

**Comment by sarah-walker-pcem** [comment] 2021-06-04 17:20
Can't reproduce here. Could you provide more details about your setup please - which version of Windows 95, what version of the Voodoo Banshee/3 driver, what DirectX version, what version of the game, etc.

**Comment by unreal9010** [comment] 2021-06-05 11:10
I've set up a new 686BX machine with PII 233, 64 MB RAM, Voodoo 3 2000 (16 MB PCI). 
I'm running Windows 95 OSR2, Direct X 6.1 (I've used 6.0 before). Voodoo 3 drivers are dated April 27th 1999. 
I've just tested GEX 3D demo and full version as well as Starshot:  Space Circus demo and each time as soon as the 3Dfx logo is about to appear PCem crashes.  
I also tried Pandemonium 2 since it's another Crystal Dynamics 3Dfx-only title and it worked great.

**Comment by shermp** [comment] 2021-06-05 22:05
> I'm using the official PCem v17 build dated December 1st 2020. Maybe the issue got fixed along the way. I haven't been able to use any version newer than the last official release since I don't know how to compile it.

Automatic builds are now available on this repository. Go to *Actions*, select a *Workflow Run*, then download one of the available artifacts.

**Comment by unreal9010** [comment] 2021-06-06 08:17
Thank you. Everything ok regarding the build (I had to manually insert libjbig-0.dll as it was not available in the archive).
The issue, however, still persists. I've just tried Gex 3D demo and full game and this time garbled artifcats appear at the center of the screen instead of 3Dfx logo for a couple of seconds and then PCem crashes. I once again tried Pandemonium ll and it worked without issues.

**Comment by sarah-walker-pcem** [comment] 2021-06-06 17:14
Ah, you were running the demo not the full game. Will try that.

(this would have been useful information to put in the description!)

**Comment by unreal9010** [comment] 2021-06-06 19:09
I ran both.

**Comment by sarah-walker-pcem** [comment] 2021-06-06 20:26
Demo does cause PCem to quit, with a "Bad CMDFIFO packet" error in the log.

**Comment by sarah-walker-pcem** [comment] 2021-06-07 19:20
Fixed in commit 84b9af3e

**Closed by sarah-walker-pcem** 2021-06-07 19:20 UTC
