### ISSUE TITLE
Blood II no music

### ISSUE THREAD

**Issue by AITUS95** [sarah-walker-pcem/pcem#130] opened 2022-03-29 20:49 UTC
**Describe the bug**
When i run blood 2 during a game the music of the game is broken, in the menu the music works perfectly, i think it is a problem related to other games too, the problem is absent in pcem v15 but with low performance.

**Emulator configuration**
 - Machine: Slot 1 - Gigabyte GA-686BX
 - CPU: Pentium II 233 mhz
 - Graphics/sound cards: Phoenix S3 Trio64 + Voodoo 2 / SB 16
 - Installed OS: Windows 98

**Host machine**
 - OS: Windows 10
 - Emulator version: Pcem V17 Stable

**Comment by leilei-** [comment] 2022-04-04 01:34
Dupe of #62

**Closed** 2022-04-04 21:36 UTC
