### ISSUE TITLE
''Configure PCem'' dialog window does not show the OK and Cancel buttons.

### ISSUE THREAD

**Issue by ambiamber** [sarah-walker-pcem/pcem#101] opened 2022-01-30 20:01 UTC
**Describe the bug**
I cannot save the configuration because the OK button is not visible on the ''Configure PCem'' window.  The ''Configure PCem'' window is smaller than I expected it to be based on seeing YT videos of PCem.

This warning message is displayed many times:
```
(pcem:49129): Gtk-WARNING **: 14:39:17.561: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)
```
**To Reproduce**
On Fedora 35 and/or Ubuntu 21.04

1. git clone https://github.com/sarah-walker-pcem/pcem.git
1. cd pcem/
1. cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release .
1. ninja
1. src/pcem
1. On the "PCem Configuration Manager" dialog, click on "New"
1. On the "New config" dialog type in "foo"
1. On the "New config" dialog click the "OK" button
1. Observe that the "Configure PCem" dialog lacks the "OK" button.
1. Observe warning messages (see above) "Negative content height -9"

**Expected behavior**
I expected to be able to save the configuration by pressing the "OK" button on the "Configure PCem" dialog.

**Screenshots**

**Emulator configuration**
N/A

**Host machine**
 - Tested on Ubuntu 22.04 and Fedora 35 with the same results.
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Jammy Jellyfish (development branch)
Release:	22.04
Codename:	jammy
```

```
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 35 (Thirty Five)
Release:	35
Codename:	ThirtyFive
```
I put the exact versions of all the development packages (dpkg and rpm) in this gist:
https://gist.github.com/ambiamber/80016803261dc8401e49159607d3b4b0
 - Emulator version
 - pcem master branch commit 26bc0c7952d4a73171df7ed0ffeaa3a1ef1787a8
 - Also tried V17

**Additional context**

**Comment by michael-manley** [comment] 2022-01-30 21:13
This is similar to menu issues. Seems to be a gtk
issue on these newer oses. Ill throw up a ubuntu vm to verify why this is going on

**Comment by ambiamber** [comment] 2022-02-01 00:09
I found out that the first time I open the ''Configure PCem'' window the OK and Cancel buttons are missing but if I close the ''Configure PCem'' window and open it again the OK and Cancel buttons show up.  
```
(pcem:15459): Gtk-WARNING **: 19:06:13.726: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node button, owner GtkButton)
```
The second time I open the ''Configure PCem'' window that warning message is not displayed.

**Comment by ambiamber** [comment] 2022-02-01 20:49
Now that I have a work-around for the "No OK button" issue that prevented me from creating a machine configuration I have found that when I do start and run an emulated machine under PCem the right click menu does not work. When I right click on the emulated machine there is no menu displayed. It doesn't matter if I capture the mouse or not, both ways no menu is displayed.

**Comment by ryanmilke** [comment] 2022-02-04 01:43
I can confirm the right click issue on Debian 11 / Gnome 3 / Wayland. Right click menu works correctly if i switch to xorg.

**Comment by michael-manley** [comment] 2022-02-05 03:00
Is the OK button issue also only on Wayland? I will admit im usually in Xorg so it could be a Wayland + GTK issue

**Comment by ryanmilke** [comment] 2022-02-05 03:46
Yes, the OK button issue also only happens for me under Wayland. I tried the latest wxWidgets (3.1.5) instead of the version shipped with Debian Bullseye (3.0.5), but no improvement.

**Comment by michael-manley** [comment] 2022-02-05 06:47
Ok, I'll do some dev in a VM with Wayland, I was a bit perplexed as my dev system is openSUSE Tumbleweed so I was for sure thinking I should see this, but being I use Xorg that explains it a bit more

**Comment by michael-manley** [comment] 2022-03-29 06:04
Closing as I will be doing updates under #128

**Closed by michael-manley** 2022-03-29 06:04 UTC
