### ISSUE TITLE
Segmentation fault: 11 on macOS

### ISSUE THREAD

**Issue by brunocastello** [sarah-walker-pcem/pcem#45] opened 2021-07-13 04:52 UTC
I am testing the recent modifications that were merged to build for macOS.

I've installed all the dependencies, compiled and installed the rom files as well.

However, when I run pcem, I get this error:

```
MacBruno-Pro:PCemV17macOS Bruninho$ ./pcem
Set fullspeed - 0 0 0
Menu item not found: 1403
Menu item not found: 1404
Menu item not found: 1403
Menu item not found: 1404
**Segmentation fault: 11**
```

I have no idea why it happens. It was working a few months ago with kyr0's and almeath's builds. Now even their builds don't work for me anymore. It happens with every other emulator configuration I try, no matter what I choose to emulate. Any ideas?

**Host machine**
 - OS: macOS Big Sur 11.4 [Intel Mac]
 - Emulator version: PCem v17
 - Any other relevant information: Late 2013 retina MacBook Pro 13-inch, i7 2.8GHz, 16GB RAM, 1TB SSD, maxed out configuration.

**Comment by brunocastello** [comment] 2021-07-28 01:38
The emulator will definitely not build/compile on macOS Intel, I think the problem is related to Xcode 12.5.1 changes and macOS SDK.

**Comment by dob205** [comment] 2021-07-28 16:00
So I decided to mess around with the configure.ac in the latest snapshot of the PCem repository and the culprit at the moment is the -O3 optimization flag inside it. Switching to -O1 made it possible to run it, but it makes the Pentium 75 which ran previously at 100% with my MacBook Pro Retina Late 2013 with a built in Intel Core i5-4258U running slower, but it runs just fine on macOS 11.5 and Xcode 12.5.1 (see: screenshot). In theory you could search for the problems inside the code caused by clang in the newest Xcode version. (see https://github.com/PCemOnMac/PCemV17macOS/issues/24)
The --enable-debug flag works too, but it runs even slower then.
![image](https://user-images.githubusercontent.com/2078457/127355342-f4c1920b-c2c4-494c-8302-cdb8d326d34e.png)

**Comment by brunocastello** [comment] 2021-07-28 17:23
That's some very encouraging news. I will try it again later with these modifications after running some errands today. Thanks for the input!

**Comment by brunocastello** [comment] 2021-07-28 18:21
@dob205 Changing the flag myself to -O1 returns this:
```
checking for sdl2 >= 2.0.1... yes
./configure: line 5845: AM_OPTIONS_WXCONFIG: command not found
./configure: line 5847: syntax error near unexpected token `$reqwx,'
./configure: line 5847: `AM_PATH_WXCONFIG($reqwx, wxWin=1)'
```

Could you attach your modified configure.ac?

**Comment by dob205** [comment] 2021-07-28 18:24
Sadly I can't attach it directly, you'll find it as a .txt that you can paste into the configure.ac and it should run.
[configure.ac.txt](https://github.com/sarah-walker-pcem/pcem/files/6895652/configure.ac.txt)

**Comment by brunocastello** [comment] 2021-07-29 04:52
Unfortunately I am stopping at the same error. First I figured out that brew has changed the wxmac name to wxWidgets, and I thought that it could be a path problem. So I decided to download and compile wxmac myself like I did for v16 before.

No luck. I get the same error as shown above about AM_OPTIONS_WXCONFIG and AM_PATH_WXCONFIG, no matter if I try with wxmac 3.0.5.1, 3.1.5 or if I try brew's version rebranded as wxwidgets. I may be missing something. (btw, openal-soft and sdl2, listed as dependencies, are installed.)

**Comment by dob205** [comment] 2021-07-29 06:03
So maybe something about the wxWidgets installation could be a problem for you. Try to purge all custom installations and all config parts and try to reinstall wxWidgets by simply running _brew install _wxmac_, which worked for me.

**Comment by mills5** [comment] 2021-07-29 08:38
Did some debugging and found a fix. The crash is related to the compiler inlining functions. You need to add `-fno-inline-functions` to your C/CXXFLAGS for -O3.

1. Open `src/Makefile` in a text editor (NOT the one in the root directory, but in the `src` directory)
2. Add `-fno-inline-functions` to your CFLAGS and CXXFLAGS (lines 815 and 819 for me, respectively)
So now yours should look like this:
`CFLAGS = -O3 -fcommon -fno-inline-functions`
`CXXFLAGS = -O3 -fcommon -fno-inline-functions`
3. make

Was able to boot into Windows 98 just fine. No need to mess with `configure.ac`.

**Comment by dob205** [comment] 2021-07-29 09:05
Can confirm it works, but I did modify the configure.ac due to future-proofing the fix, since it affects mostly the --enable-release-build option for the ./configure step in the afromentioned file. The only small gripe was a one-time crash with my Win98 SE machine, that has a Pentium 75 and Voodoo Banshee installed. Anyway the performance seems to be restored to previous levels on my machine. So to conclude, the most recent Xcode update made the PCem source choke up without `-fno-inline-functions`. I wonder, if it affected Apple silicon, too. If it is okay for you, I'd commit the changed cflags into the `configure.ac` file and backport it into the PCemV17macOS project.

**Comment by brunocastello** [comment] 2021-07-29 17:18
After doing the changes above to Makefile, this is what I get. I don't know why it has to go after the macOS SDK ?

![Screen Shot 2021-07-29 at 2 16 41 PM](https://user-images.githubusercontent.com/23453202/127536069-e3bb49ea-3a92-4b41-82d2-aeaf08ed0d23.png)

**Comment by brunocastello** [comment] 2021-08-23 02:04
The thing still fails to compile even with the modification from the PR above, even though I have met all the three dependencies (SDL2, OpenAL-Soft, and wxWidgets 3.1.5). It crashes after calling "make", complaining about some WXCONFIG parameter.

**Comment by ndbroadbent** [comment] 2021-08-23 03:18
@brunocastello I was just able to get pcem to compile on the latest MacOS (Big Sur 11.5.2.) I followed the instructions at the bottom of https://github.com/PCemOnMac/PCemV17macOS (the *Under macOS 11 (Big Sur):* section.) After installing `wxWidgets-3.0.5.1 `, you should be able to configure / ompile pcem like this:


```
./configure --enable-networking --enable-release-build --with-wxdir=/usr/local/Cellar/wxmac/3.0.5.1_1/bin/
make
```

**Comment by ndbroadbent** [comment] 2021-08-23 03:20
However I still get a `Segmentation fault: 11` crash whenever I try to run a Pentium CPU. It seems to work fine for 486 though. Will try the `-O1` flag

**Comment by dob205** [comment] 2021-08-23 09:41
@ndbroadbent It's not really the issue with the `-O3` flag, rather it's a problem with the inline optimizations, so please add `CFLAGS = -O3 -fcommon -fno-inline-functions` and `CXXFLAGS = -O3 -fcommon -fno-inline-functions` inside the `configure.ac` or the Makefile as discovered by @mills5 (see https://github.com/sarah-walker-pcem/pcem/issues/45#issuecomment-888922599) when you encounter the `enable-release-build` condition inside that file or add it manually to your compile. Especially after adding a manual `-mtune=native` I'm able to run up to a Mobile Pentium MMX 120 on my base processor 13" Late 2013 MacBook Pro Retina. I wonder if Apple Silicon seems to be unaffected by the inline optimizations.

**Comment by brunocastello** [comment] 2021-09-16 05:23
Any news on it? I am still unable to compile it due to the errors I pointed out above in a screenshot; seems related to a macOS SDK but I have no clue about what could be. Xcode works fine for other projects though.

**Comment by brunocastello** [comment] 2021-09-27 01:47
I'm now on latest macOS Big Sur 11.6 and Xcode 13.0, and still unable to compile PCem. Apparently its a problem between the code for the cdrom images and macOS SDK as seen in the previous screenshot above.

**Comment by brunocastello** [comment] 2021-09-30 17:54
Anyone? With any idea of why I am unable to compile or run the app since July?

**Comment by brunocastello** [comment] 2021-10-07 21:18
This thing sure fails to compile on Big Sur 11.6 and Xcode 13.

**Comment by brunocastello** [comment] 2021-11-25 15:45
@dob205 hi, do you have an working PCem build for the M1? I finally got an MB Air to use. I did try to build it myself but whenever I try to use any of the available Voodoo cards, PCem crashes itself. Either a build or a script on how to build it myself, I'd appreciate one or both. Thanks in advance for the reply.

**Comment by brunocastello** [comment] 2022-02-14 16:43
Anyone having luck with that on M1 Macs?

**Comment by michael-manley** [comment] 2022-04-13 04:16
Closing ref #131 for the Mac Megaticket

**Closed by michael-manley** 2022-04-13 04:16 UTC
Labels: bug
