### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by dananothername** [sarah-walker-pcem/pcem#147] opened 2022-05-22 10:24 UTC
![shot-2022-05-22_06-21-39](https://user-images.githubusercontent.com/101902085/169690751-7a90f413-efd9-4a3c-b4ee-7279eda4f391.jpg)
did i miss something like CMakeLists.txt

**Comment by Derailedzack** [comment] 2022-05-23 01:59
Try changing into the src directory.

**Comment by dananothername** [comment] 2022-05-23 21:03
sorry wrong screen shot
![Uploading shot-2022-05-23_04-40-38.jpg…]()
here is the one

**Comment by dananothername** [comment] 2022-05-23 21:04
sorry wrong screen shot
![Uploading shot-2022-05-23_04-40-38.jpg…]()

here is the one

**Comment by bartman081523** [comment] 2022-05-26 06:41
You have a old v17 source tree. 
git clone https://github.com/sarah-walker-pcem/pcem
and do the build there

**Comment by dananothername** [comment] 2022-05-27 08:53
![shot-2022-05-26_16-44-23](https://user-images.githubusercontent.com/101902085/170666332-099d1170-baa7-49fa-af99-11924efc1095.jpg)
still didn't work

**Comment by bartman081523** [comment] 2022-05-27 09:08
`sudo apt install ninja-build`
and in the git directory
`ninja`

**Comment by Derailedzack** [comment] 2022-05-27 10:38
Do you have a C compiler?

**Comment by dananothername** [comment] 2022-05-27 12:09
where is this git directory

**Comment by JosepMaJAZ** [comment] 2022-05-27 13:52
You were told to try on the src subfolder. Don't do it.
Try it from the pcem-dev folder

**Comment by dananothername** [comment] 2022-05-27 14:02
![Uploading shot-2022-05-27_09-59-21.jpg…]()

**Comment by Derailedzack** [comment] 2022-05-27 14:05
You need to install OpenAL.

**Comment by bartman081523** [comment] 2022-05-27 18:25
@JosepMaJAZ JosepMaJAZ
> You were told to try on the src subfolder. Don't do it.
I never wrote that. I mean the (git) directory that got git cloned. 
@dananothername 
!watch out for your ubuntu release in line 2 (impish, highest available implied here)
```
sudo apt-key adv --fetch-keys https://repos.codelite.org/CodeLite.asc
sudo apt-add-repository 'deb https://repos.codelite.org/wx3.1.6/ubuntu/ impish universe'
sudo apt install wx3.1* libwx*3.1* wx-common libopenal-dev libsdl2-dev build-essential cmake ninja-build git
git clone https://github.com/sarah-walker-pcem/pcem
cd pcem
cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release .
ninja
./src/pcem
```

**Comment by dananothername** [comment] 2022-05-28 20:13
do you mean i must edit line 2?
cuz i have ubuntu 20.04

**Comment by bartman081523** [comment] 2022-05-29 04:27
> do you mean i must edit line 2?
> cuz i have ubuntu 20.04
yes. 
for 20.04 (focal)

```
sudo apt-key adv --fetch-keys https://repos.codelite.org/CodeLite.asc
sudo apt-add-repository 'deb https://repos.codelite.org/wx3.1.6/ubuntu/ focal universe'
sudo apt install wx3.1* libwx*3.1* wx-common libopenal-dev libsdl2-dev build-essential cmake ninja-build git
git clone https://github.com/sarah-walker-pcem/pcem
cd pcem
cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release .
ninja
./src/pcem
```

**Comment by dananothername** [comment] 2022-05-31 12:01
thanks it worked 
now for the rom 
i think i have it witch is "JRT"
but where to place it

**Comment by bartman081523** [comment] 2022-05-31 14:40
roms are in ~/.pcem/roms

**Comment by dananothername** [comment] 2022-06-04 19:52
what does the extension should look like

**Comment by bartman081523** [comment] 2022-06-04 20:39
Download the roms from:
https://github.com/BaRRaKudaRain/PCem-ROMs/releases
unzip the roms to ~/.pcem/roms


Am Sa., 4. Juni 2022 um 21:53 Uhr schrieb dan_crim ***@***.***

**Comment by ruben-balea** [comment] 2022-06-04 20:52
> roms are in ~/.pcem/roms

Please delete you **last** comment you made 10 minutes ago, links to **copytighted** materials **are not allowed here**.

**Comment by bartman081523** [comment] 2022-06-04 21:10
@ruben-balea they are in GitHub, this thread ist in GitHub. Where does it say, links to Rom collection is not allowed? GitHub? Thema why are the Rom collection can bei hosted in GitHub?

**Comment by ruben-balea** [comment] 2022-06-04 21:18
The project leaders said so, others can do what they want in their own github accounts but in this project there are certain rules.

[https://github.com/sarah-walker-pcem/pcem/blob/dev/README.md](url)

**Comment by ruben-balea** [comment] 2022-06-04 21:22
> @ruben-balea the Roms are on GitHub, this thread is on GitHub. Where does it say, links to Rom collection is not allowed? GitHub? Then why are the Rom collection can be hosted on GitHub?
> 
> I see, only you say it. Then I leave it. I am trying to help this User here.

The project leaders said so, others can do what they want in their own github accounts but in this project there are certain rules.

The file https://github.com/sarah-walker-pcem/pcem/blob/dev/README.md says so:

PCem is licensed under GPL v2.0, see [COPYING](https://github.com/sarah-walker-pcem/pcem/blob/dev/COPYING) for more details.

You can submit patches on our [forum](https://pcem-emulator.co.uk/phpBB3). Before you do, please note the [guidelines](https://pcem-emulator.co.uk/phpBB3/viewtopic.php?f=3&t=5) for submitting patches.

❗ Note: NO COPYRIGHTED ROM FILES ARE INCLUDED NOR WILL THEY BE. PLEASE DO NOT ASK FOR THEM.

**Comment by ruben-balea** [comment] 2022-06-04 21:25
> @ruben-balea the Roms are on GitHub, this thread is on GitHub. Where does it say, links to Rom collection is not allowed? GitHub? Then why are the Rom collection can be hosted on GitHub?
> 
> I see, only you say it. Then I leave it. I am trying to help this User here.

See also the project rules here: https://www.pcem-emulator.co.uk/phpBB3/viewtopic.php?p=15665#p15665

**Comment by bartman081523** [comment] 2022-06-04 21:32
I never included copyrighted Roms, nor I asked for the inclusion. 
You are always free to report my post to GitHub.

**Comment by bartman081523** [comment] 2022-06-04 21:39
> See also the project rules here: https://www.pcem-emulator.co.uk/phpBB3/viewtopic.php?p=15665#p15665

No, why? GitHub ist GitHub, not phpbb3.

**Comment by bartman081523** [comment] 2022-06-04 21:42
> > @ruben-balea the Roms are on GitHub, this thread is on GitHub. Where does it say, links to Rom collection is not allowed? GitHub? Then why are the Rom collection can be hosted on GitHub?
> > 
> > I see, only you say it. Then I leave it. I am trying to help this User here.
> 
> See also the project rules here: https://www.pcem-emulator.co.uk/phpBB3/viewtopic.php?p=15665#p15665

No. 

Are you happy you flooded a help thread?

**Comment by ruben-balea** [comment] 2022-06-04 21:52
> > > @ruben-balea the Roms are on GitHub, this thread is on GitHub. Where does it say, links to Rom collection is not allowed? GitHub? Then why are the Rom collection can be hosted on GitHub?
> > > I see, only you say it. Then I leave it. I am trying to help this User here.
> > 
> > 
> > See also the project rules here: https://www.pcem-emulator.co.uk/phpBB3/viewtopic.php?p=15665#p15665
> 
> No.
> 
> Are you happy you flooded a help thread?

The user has those files published on his github page if they delete take it down he does not lose anything, but if the PCem project is canceled due to breaking the rules, we will all lose, I don't know why it is so hard for you to understand.
If you want your own rules, you are free to make your own fork of the project.

But you should know that I have nothing against you or against helping others, I just wanted you to know the rules, please don't take it personally.

**Comment by ruben-balea** [comment] 2022-06-04 21:55
> > > @ruben-balea the Roms are on GitHub, this thread is on GitHub. Where does it say, links to Rom collection is not allowed? GitHub? Then why are the Rom collection can be hosted on GitHub?
> > > I see, only you say it. Then I leave it. I am trying to help this User here.
> > 
> > 
> > See also the project rules here: https://www.pcem-emulator.co.uk/phpBB3/viewtopic.php?p=15665#p15665
> 
> No.
> 
> Are you happy you flooded a help thread?

Don't worry about flooding the thread, all those posts can be hidden or deleted once the issue is fixed

**Comment by dananothername** [comment] 2022-06-05 20:28
anyway 
i have seen a guide of how to use pcem by guy named billy
but his guide for windows
so i end here 
![shot-2022-06-05_13-20-53](https://user-images.githubusercontent.com/101902085/172069261-012b2bf2-0689-4458-bfdc-c07d7e66cf69.jpg)
how to drage or choose the iso for it

**Comment by bartman081523** [comment] 2022-06-06 00:25
@dananothername 

You can right-click in the pcem window, when the mouse is not captured, and insert the .iso file in the virtual drive.

**Comment by dananothername** [comment] 2022-06-07 11:01
![shot-2022-06-06_21-21-54](https://user-images.githubusercontent.com/101902085/172363723-20ea4923-1dbf-4b4b-9f34-da0e9ce86c30.jpg)
here is what happen for right click
![shot-2022-06-06_20-56-43](https://user-images.githubusercontent.com/101902085/172363811-fc6d288e-8d47-4da8-b9f5-eeab0407675c.jpg)
and after choosing iso winXP it still ask for bootable drive
![shot-2022-06-05_13-20-53](https://user-images.githubusercontent.com/101902085/172364077-8bfd2a7a-dc7e-4f89-9447-409c765cd592.jpg)

**Comment by bartman081523** [comment] 2022-06-07 14:17
@dananothername I dont know whats wrong with your Windows XP image. Try another image.
By the way, when you want to run XP, you have far better performance with VirtualBox, just sayin.

**Comment by dananothername** [comment] 2022-06-09 11:27
- i have tried win 2000 now same issue 
it shows this - i don't see that option in this bios
- 
![shot-2022-06-09_06-37-07](https://user-images.githubusercontent.com/101902085/172836145-eaea3ca9-3b25-4f16-a134-4cd0b1b6c762.jpg)

![shot-2022-06-09_06-37-07](https://user-images.githubusercontent.com/101902085/172836103-22a2b44b-7977-4c2d-9630-530a60aaa457.jpg)
- my pc is cursed i can't run vertial box
-

**Comment by dananothername** [comment] 2022-06-09 11:30
![shot-2022-06-09_06-38-23](https://user-images.githubusercontent.com/101902085/172836428-bac0db99-5da0-4c94-bbe5-187c3c7150f2.jpg)
this bios with DEL

**Comment by bartman081523** [comment] 2022-06-09 15:29
I have the option for Advanced features and then Boot Order in Machine "Gigabyte GA-686BX", maybe you try that one. 
Whats wrong with VirtualBox on your computer?

**Comment by ruben-balea** [comment] 2022-06-09 17:07
There were Windows XP boot floppies for BIOS without CD-ROM Boot, you can download them here:

https://www.allbootdisks.com/download/xphome.html
https://www.allbootdisks.com/download/xppro.html

If you have XP Home you must use the XP Home boot floppies, for XP Professional must use the XP Professional boot floppies.

Also you must use the boot floppies corresponding to your Windows XP service pack, there were made only for XP without service pack, XP with SP1 and XP with SP2.

If you have a XP with SP3 CD-ROM try SP2 boot floppies, if they don't work find a XP SP2 CD-ROM and update it later to SP3 using this file: https://www.catalog.update.microsoft.com/Search.aspx?q=kb936929

Select "Diskette Images" and download all six floppy images, you have to boot from disk1 and then swap the images as the Windows installer tells you.

**Comment by ruben-balea** [comment] 2022-06-09 17:23
> 



> ![shot-2022-06-09_06-38-23](https://user-images.githubusercontent.com/101902085/172836428-bac0db99-5da0-4c94-bbe5-187c3c7150f2.jpg) this bios with DEL

Use left and right arrow keys to move to the **Main** page and then use up and down arrow keys to choose **Boot Options** and press enter:

![Screenshot from 2022-06-09 19-10-20](https://user-images.githubusercontent.com/98262033/172905410-f086ccb1-52a0-4dba-b706-fdae0568ea66.png)

Then select First Boot Device, press enter and select CD-ROM:

![Screenshot from 2022-06-09 19-10-28](https://user-images.githubusercontent.com/98262033/172905858-b5ae3766-d1db-4ed8-af5f-43d1af0b8e6e.png)

Press enter again to confirm the changes:

![Screenshot from 2022-06-09 19-10-36](https://user-images.githubusercontent.com/98262033/172906115-753a2ffc-17d9-4556-a6f3-d80826cd258e.png)

Then press F10 to save the changes and exit, press enter again to save changes and continue:
![Screenshot from 2022-06-09 19-10-45](https://user-images.githubusercontent.com/98262033/172906372-0a43a0a4-cd4b-4fd8-bd25-258dc6e58b28.png)

The machine will reboot and boot from the CD-ROM drive.

![Screenshot from 2022-06-09 19-22-46](https://user-images.githubusercontent.com/98262033/172907321-6e57c95b-d148-495b-b94c-ad7a94a6e53a.png)

**Comment by dananothername** [comment] 2022-06-10 13:08
the last comment helped 
i am now trying product keys
also the mouse got stuck in the window
how to move it out

**Comment by ruben-balea** [comment] 2022-06-10 20:37
To release the mouse capture press **Control + End**

The title bar of the window displays that information, but depending on the size of the window and how long the CPU and motherboard model names are, that information may be (partially) hidden due to lack of space.

Also if you are emulating a Microsoft 2-button mouse (serial) or a 2-button mouse (PS/2) the middle mouse button/wheel is not used by PCem and you can use it to release the mouse capture.

On the other hand if you're emulating a Mouse Systems 3-button mouse (serial) or a Microsoft Intellimouse (PS/2) the middle mouse button/wheel is used by PCem and **can't** be used to release the mouse capture, in that case only the keyboard shortcut works.

![pcem_release_mouse](https://user-images.githubusercontent.com/98262033/173144082-ed3e7143-255c-47ec-a7c2-3e1c759585eb.png)

**Comment by bartman081523** [comment] 2022-06-15 05:09
If you want to Play an WinXP Java Game, the fastest way to play, would be to use Java in Windows XP in Oracle VirtualBox. Oracle VirtualBox reaches about 80-90% real speed of the original, where Pcem in Pentium II 300, is about 50-70% (!of a Pentium II 300).

**Comment by dananothername** [comment] 2022-06-15 20:22
Is there a way to reach it's storage from linux file manger

**Comment by ruben-balea** [comment] 2022-06-15 23:31
First remember to do it only while PCem is **not** running, if you try to access it with two operating systems at the same time you can corrupt the file system of the disk image and lose or damage its contents.

I'm not sure there is any tool to do it from the graphical interface, you can mount the images as another drive using the built-in terminal commands, but these have limitations on the types of images they support, for different formats you need to install additional packages and use the specific tool for each format...
It might be best to install a tool that supports any disk image format to use them all without having to know the specifics of each format.
The **libguestfs-tools** package includes the **guestmounts** tool which seems to do a good job of supporting all kinds of disk images.
Here is a specific tutorial for Ubuntu users that explains how to install and use guestmounts:
https://www.how2shout.com/linux/mount-virtual-hard-disk-vhd-file-ubuntu-linux/

* I have not tried it but it is recommended in many forums so I suppose it is one of the most practical and/or easy to use tools to mount disk images.
* On Windows I use a program called Winimage (https://www.winimage.com/) perhaps if you install Wine you can get it working on Linux

**Comment by dananothername** [comment] 2022-06-20 22:21
i want to install this one 
https://github.com/TASEmulators/pcem/releases/tag/17%2Bst-1

**Comment by dananothername** [comment] 2022-06-20 22:22
![shot-2022-06-18_18-35-58](https://user-images.githubusercontent.com/101902085/174684139-6942c383-b8b3-431c-a3e9-e5ae5b054616.jpg)
but it doesn't contain cmake files 
a command is missing

**Comment by Derailedzack** [comment] 2022-06-22 05:33
That's because that version of pcem doesn't use CMake as the build system. It uses autotools.

**Comment by dananothername** [comment] 2022-06-22 21:06
last version is 17

**Comment by michael-manley** [comment] 2022-06-24 09:38
We dont support nor will we give help for alternative PCem builds. If you want support for that please message them. I'm closing this as this isn't a bug report, but a question, and GitHub is for development tasks only.

**Closed by michael-manley** 2022-06-24 09:38 UTC
Labels: question
