### ISSUE TITLE
Mental Math Games by Waterford Institute freezes on the mouse maze if both sound and background music is turned ON.

### ISSUE THREAD

**Issue by RandomKorok** [sarah-walker-pcem/pcem#163] opened 2022-06-29 07:28 UTC
Host: Windows 10:  I7 10th core  2.8GHZ.
Guest:  Windows 98SE or anything below that on either Socket 7 or Socket 8 any bios. 

Behavior:  Mental Math Games by Waterford: 

 I have the ISO version of it and CD both have this same bug which isn't on the appropriate hardware that when you turn on background music the mouse maze game starts to show up as soon as the door opens the mouse doesn't show up. Music still plays but the game is essentially frozen.  You can have either Backround SFX OR Music turned on but NOT both or that behavior happens.:

The Streaming only one has the very same issue:  

Expected Behavior:  The mouse comes out a random door and you control the mouse by typing in the answer to a math problem in one of four directional arrows with both SFX AND Music turned on to hear the door opening whilst music is playing.  
 Typing the same answer twice will speed up the mouse in that direction of travel.

**Comment by unreal9010** [comment] 2022-06-29 12:32
Please provide more information about your guest machine, including emulated CPU, video card and (especially important) sound card. At the moment it's impossible to determine whether this is a PCem or hardware issue that could be replicated on real hardware.

**Comment by unreal9010** [comment] 2022-06-29 12:36
Also: REMOVE any links to copyrighted software not offered by the copyright holder.

**Comment by RandomKorok** [comment] 2022-06-29 12:37
> Also: REMOVE any links to copyrighted software not offered by the copyright holder.

Archive.org is legal.

**Comment by unreal9010** [comment] 2022-06-29 12:41
Archive.org is an open platform that anyone could upload to. Just because files get uploaded there, doesn't mean they're legal.
The only time files on Archive.org are legal is when they're offered by the copyright holder or in accordance with their approval.

**Comment by RandomKorok** [comment] 2022-06-29 12:44
Why are you being so bossy and mean about it anyways? It’s just a stupid game from the late 80s that’s stream only. Your not the FBI. I’ll remove it but you don’t need to be a prick about it. If I didn’t put it up you wouldn’t know what the hell I was talking about on my problem to begin with.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by unreal9010** [comment] 2022-06-29 12:48
I'm not being bossy about it. it's just that there are certain copyright-related rules here (which I didn't come up with, btw).

**Comment by RandomKorok** [comment] 2022-06-29 12:49
As for my

> Please provide more information about your guest machine, including emulated CPU, video card and (especially important) sound card. At the moment it's impossible to determine whether this is a PCem or hardware issue that could be replicated on real hardware.

I already said it but I don't think you read it.  Socket 7 or 8 any bios.  3DFX Voodoo 3 which I forgot to put in and Sound Blaster 16 which the game needs hence you can only do music OR sound but not both.  The mouse won't show up out the door when both are selected but if one OR the other are selected you can control the little mouse creature.

**Comment by unreal9010** [comment] 2022-06-29 12:59
What kind of hardware was this game originally played on? It could be that that any Socket 7 machine is simply too powerful for it. Also make sure to have enough conventional memory available. What year was this game released in?

**Comment by RandomKorok** [comment] 2022-06-29 13:07
Actually I don't know what socket

> Does this game make any use of UniVBE? Note that Voodoo 3 is not compatible with UniVBE and tends to cause issues with games that depend on it.

What's THAT? 😕

**Comment by unreal9010** [comment] 2022-06-29 13:13
Nah, definitely not given that it's from 1993. UniVBE came out later. My bad. 
Anyway - have you tried running the game with a video card from around the time the game came out to see if it makes any difference?

**Comment by RandomKorok** [comment] 2022-06-29 13:16
> Nah, definitely not given that it's from 1993. UniVBE came out later. My bad. Anyway - have you tried running the game with a video card from around the time the game came out to see if it makes any difference?
S3 Virge seems to have helped actually.  I'm going to bed now as my eyes are miserable.  :(  But I got the mouse to work. Either it's the S3 Virge that helped or the fact i'm doing it on a  Epox Cyris PR66 if that is any good.  It seems to help.

**Comment by unreal9010** [comment] 2022-06-29 13:20
Well, given that the game works with a Cyrix 6x86 processor it means it isn't so picky about working with later hardware. 
The ViRGE seems to have solved the issue here.

**Comment by eddlang** [comment] 2022-06-29 16:12
Github is for posting confirmed bugs or feature requests. When you want to investigate and make sure it is actually one, first post it somewhere like the pcem forums or vogons.

**Comment by KoghaandSooga** [comment] 2022-07-18 22:23
> Github is for posting confirmed bugs or feature requests. When you want to investigate and make sure it is actually one, first post it somewhere like the pcem forums or vogons.

Both are dead. I posted other issues on both and got no replies there. Either I'm hated or they are dead not sure which.  I got hacked by Microsoft Update and Dad had to redo both my computer and email.  As soon as my computer restarted it couldn't find it and Dell tried to save my files but it booted me to Win 11 instead of 10 so Dad went thru hell to get me back to 10 to put a long story short as none of my USB devices work with 11.   Anways I'm having the issue again I don't know if I should make a fresh thread.

**Comment by ruben-balea** [comment] 2022-07-19 02:59
> > Github is for posting confirmed bugs or feature requests. When you want to investigate and make sure it is actually one, first post it somewhere like the pcem forums or vogons.
> 
> Both sites are dead. I posted other PCEM issues on both and got no replies there. Either I'm hated or they are dead not sure which. I got hacked by Microsoft Update and Dad had to redo both my computer and email so I can't login to my old account here:
> 
> As soon as my computer restarted it couldn't find it and Dell tried to save my files but it booted me to Win 11 instead of 10 so Dad went thru hell to get me back to 10 to put a long story short as none of my USB devices work with 11 outside of Steam which is why I went back to 10 in the first place. My new PC I got earlier in the year came with 11 so we got it to go to 10 a long time ago and Dell forced it back to 11 after the update crash.
> 
> Anways I'm having the issue of again of which started this thread I don't know if I should make a fresh thread.

Please register on the PCem forum http://pcem-emulator.co.uk/phpBB3/ucp.php?mode=register and describe the problem with this game there, I will explain how you can solve it.

**Comment by unreal9010** [comment] 2022-07-19 07:05
Please stop spamming and close the issue since it's not a PCem one due to being a real-life old software with newer hardware conflict. In any case, nothing can/could be done about it. PCem is about accurately emulating old hardware, with all their ups and downs including. I can't get Constructor to work with Voodoo 3 or Banshee under PCem either nor could I on my old machine with Voodoo 3 from back in the day due to the card's incompatibility with UniVBE.

**Comment by unreal9010** [comment] 2022-07-19 07:21
At the bottom of the screen, in particularly left of the "Comment" button, there is another button that says "Close issue". You obviously have to click that one. And no, you haven't had an issue with some things not being compatible with PCem. As per your own "discovery", the thing actually wasn't compatible with certain hardware. There's a difference.

**Comment by KoghaandSooga** [comment] 2022-07-19 07:25
Screenshot below of closing topic issue: I just remembered Snipping Tool:

Hmmm 'left' of the comment button. The only thing I see is this:  

"Remember, contributions to this repository should follow our [GitHub Community Guidelines](https://docs.github.com/articles/github-community-guidelines)." and above that something about attaching files by dragging and dropping them.  Sorry but I don't see it. 

![No Close button](https://user-images.githubusercontent.com/109556152/179691403-9c874442-5bbc-4916-af60-b51a63f61382.PNG)

**Comment by unreal9010** [comment] 2022-07-19 07:29
First, go to the issue that you are supposed to close and then click the "Close issue" button as shown below.
![close issue](https://user-images.githubusercontent.com/84349460/179692188-568c838c-db2e-4a02-bb53-7465d2441212.jpg)
.

**Comment by KoghaandSooga** [comment] 2022-07-19 08:19
![Original Issue](https://user-images.githubusercontent.com/109556152/179702018-d630b531-c4f4-455b-aa66-1f6555732c52.png)

Is this what you mean by the original issue? I just figured out! I am not logged in with that one and like I said I cannot log in because my PC got hacked if you read my email and Dad had to redo it to another one which is what I'm using now.  I'm very sorry about this.  :( That account is toast that started this issue.  I had to make another account just to let you know that.

**Comment by KoghaandSooga** [comment] 2022-07-19 08:29
Oh and for a final measure here is a screenshot of the problem I mentioned on my other account for future reference just in case anyone else runs into this trouble:  
![image](https://user-images.githubusercontent.com/109556152/179704575-74ce4ba3-17f2-4f34-be99-7f01fc978f6e.png)

**Comment by KoghaandSooga** [comment] 2022-07-19 11:24
Can’t. Not able to log into the account if you read what I said: but I just won’t post as I also earlier said.  My old account is tied to an email I can no longer access.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by KoghaandSooga** [comment] 2022-07-19 11:30
Can you close it or am I screwed here? If neither of us can't close it how about I just don't bother with this thread anymore like I said?

**Comment by unreal9010** [comment] 2022-07-19 11:38
Wait for the admin to close it, then.

**Comment by KoghaandSooga** [comment] 2022-07-19 11:40
> Wait for the admin to close it, then.

Can he do that? Thanks! Do you think the update that screwed me was this one in June that I wounded up getting late? It had a LOT of complaints since it was a big one as I don't recall getting any in June on my PC.  https://www.windowslatest.com/2022/06/19/microsoft-confirms-new-issues-in-windows-10-june-2022-updates/  This sort of sounds like it but it hit me a few days ago and Dad went thru hell to get things back. Dell tried their dam best to help but it all went to Windows 11 which my PC came with so no fault on their end.  Windows 11 doesn't play well with my USB devices yet.

**Comment by unreal9010** [comment] 2022-09-10 11:48
@michael-manley : Please close this issue since it has nothing to do with PCem. It's a duplicate of issue #165.

**Closed** 2022-09-11 06:31 UTC
