### ISSUE TITLE
Cyrix III Bios can't save and exit..

### ISSUE THREAD

**Issue by KoghaandSooga** [sarah-walker-pcem/pcem#257] opened 2024-04-27 10:02 UTC
Now that I'm feeling better again how the hell do I close this issue? 

When you boot into bios then try to save and exit you can't type anything in. The arrow keys work fine so that means the keyboard is receiving input on both my host and virtual CPU in that regards but letters don't seem to work for that bios.  Other bios as far as I know don't have this bug.
 
![CyrixIII Bios](https://github.com/sarah-walker-pcem/pcem/assets/109556152/29a82152-46cd-4c3e-a5f9-e2869be0a03d)

Here's my config file too if you'd like that.  I almost forgot! Never mind it won't let me upload it on here its says "We don't support that file  type" like how are people suppose to upload their PCEM config files for others to replicate errors?

**Comment by KoghaandSooga** [comment] 2024-04-27 10:05
Hmmm I'll try the picture again. 
![CyrixIII Bios](https://github.com/sarah-walker-pcem/pcem/assets/109556152/a233d043-f26c-4225-9079-ec5868f6dc45)

I think this one is much better. How do I delete the other?

**Comment by unreal9010** [comment] 2024-04-27 11:32
There is no such bug. I've just tried a GA-686BX configuration with Cyrix III CPU and I can confirm that everything works perfectly fine. 
The arrow and character keys both work as they should and I can normally save any changes I make. 
Something may be wrong with your BIOS file or perhaps it's in read-only mode.

**Comment by KoghaandSooga** [comment] 2024-04-27 13:19
> There is no such bug. I've just tried a GA-686BX configuration with Cyrix III CPU and I can confirm that everything works perfectly fine. The arrow and character keys both work as they should and I can normally save any changes I make. Something may be wrong with your BIOS file or perhaps it's in read-only mode.

If that's the case what's the bin file called so I can find it and see?

I can get the arrow keys to work but not the input. I just use the 'official' unofficial roms if you know what I mean that are on Github. Are you using that set as that's the only ones I know of.

**Comment by unreal9010** [comment] 2024-04-27 15:32
No, I'm not using that set. I have my own file. 
I would recommend to obtain the bios from manufacturer's website. As far as I know, it's still available.

**Comment by KoghaandSooga** [comment] 2024-04-27 19:23
> No, I'm not using that set. I have my own file. I would recommend to obtain the bios from manufacturer's website. As far as I know, it's still available.

Edit: New problem not sure if it warrants a new thread or not:  Here's a picture of a weird error message when attempting to load XP in Cyrix III.  
![XP Cyrix III install error](https://github.com/sarah-walker-pcem/pcem/assets/109556152/52baeb14-eb6e-40f9-be39-ea8a667e8266)


Actually I got it working! It turns out that my BOTW CEMU Second Wind mod was left on and was for some reason interfering with  it. Not sure why it would with that particular bios but turning CEMU off fixed it.  

One interesting note is if you turn STEAM on and PCEM on then for some reason my Switch PRO (or any) controller automatically works on PCEM and you can 'sort of' navigate Windows even that way with it. Weird.   If you use the manufacturers bios instead of 'that' rom set would it affect performance in anyway just curious.

**Comment by unreal9010** [comment] 2024-04-27 20:18
The message you're seeing has nothing to do with PCem. It's a known hardware issue (and which is accurately emulated by PCem) so please don't open another thread. In fact, you should close this one since your issue is not related to PCem.

https://forum.vcfed.org/index.php?threads/operating-system-compatibility-on-early-x86-32-chips.74632/#post-904934

**Comment by unreal9010** [comment] 2024-04-27 20:48
Furthermore, the CPUs that PCem currently emulates are too slow to offer a decent gaming performance under Windows XP.
Back in the day, I owned a PC with 1GHZ AMD Duron processor, 256 MB RAM, GeForce 4 MX and a mid-range MSI board and the performance was still far from desirable.

**Comment by KoghaandSooga** [comment] 2024-05-06 10:48
> Furthermore, the CPUs that PCem currently emulates are too slow to offer a decent gaming performance under Windows XP. Back in the day, I owned a PC with 1GHZ AMD Duron processor, 256 MB RAM, GeForce 4 MX and a mid-range MSI board and the performance was still far from desirable.

One last post. How come this guy contradicts himself? "Thankyou for the informations, however in certain cases even if the os refuses to install, once if its installed, it works with the questioned cpu. Therefore i am currently canot red out the 6x86 and 5x86 and geode cpus based on that."

Does it install or not? One sentence he believes it won't install but another it does install. Either the hardware is supported or it isn't and according to the first post it seems it isn't which may be my issue? I didn't know that about Cyrix and furthermore didn't even know Cyrix at the time.  Where we lived in the sticks partes were limited in the mountains of Californ Eye A. 

After your reply I'll close this if you tell me how? I don't see any close thread icon. Is deleting the same thing? 

Someone's being nasty here and I didn't do anything wrong except ask a hardware question there is no mention of. The thread linked is referring to an old Cyrix which of course XP won't work on but I'm using a newer Cyrix on PCEM.

**Comment by KoghaandSooga** [comment] 2024-05-15 11:27
> The message you're seeing has nothing to do with PCem. It's a known hardware issue (and which is accurately emulated by PCem) so please don't open another thread. In fact, you should close this one since your issue is not related to PCem.
> 
> https://forum.vcfed.org/index.php?threads/operating-system-compatibility-on-early-x86-32-chips.74632/#post-904934

That thread mentions an old Pentium 1 era hardware. I'm using Cyrix III/500 which I believe came out later which should support it due to it's much faster speed. I would never use a Pentium 1 era for actual serious XP use I'd be caught dead. Pentium II is actually a lot better for XP for speeds above 300mhz.  PIII is ideal but PII is definitely in the bearable category rage.

**Comment by KoghaandSooga** [comment] 2024-05-15 11:29
Bottom line is It seems Github is a very toxic place to be if you need simple help unless you prove your a God programmer knowing 100s of lines of code which I don't. Sorry but I can't help who I am.

**Closed as completed** 2024-05-15 11:32 UTC
